#!/usr/bin/env bash
set -Eeuo pipefail

STATE_DIR="$HOME/.config/arma3-tools-linux"
STATE_FILE="$STATE_DIR/state"
MAPPINGS_FILE="$STATE_DIR/original-drive-mappings"
APP_DIR="$HOME/.local/share/applications"
DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || true)"
DESKTOP_DIR="${DESKTOP_DIR:-$HOME/Desktop}"

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

if (( EUID == 0 )); then
    die "Do not run this uninstaller with sudo or as root."
fi

if [[ ! -f "$STATE_FILE" ]]; then
    die "No installation state was found at $STATE_FILE."
fi

# This file is generated by install.sh with shell-escaped path values.
# shellcheck disable=SC1090
source "$STATE_FILE"

run_proton() {
    timeout 45s env \
        STEAM_COMPAT_CLIENT_INSTALL_PATH="$STEAM_CLIENT_ROOT" \
        STEAM_COMPAT_DATA_PATH="$COMPAT_ROOT" \
        STEAM_COMPAT_APP_ID="233800" \
        SteamAppId="233800" \
        SteamGameId="233800" \
        "$PROTON" run "$@"
}

if [[ -x "${PROTON:-}" && -d "${COMPAT_ROOT:-}" ]]; then
    printf 'Removing registry settings...\n'
    for registry_view in 32 64; do
        run_proton reg.exe delete \
            'HKLM\Software\BIStudio\TextureConvert' \
            /v MAIN /f "/reg:$registry_view" >/dev/null 2>&1 || true
        run_proton reg.exe delete \
            'HKLM\Software\BIStudio\TextureConvert' \
            /v configPath /f "/reg:$registry_view" >/dev/null 2>&1 || true
        run_proton reg.exe delete \
            'HKLM\Software\Bohemia Interactive\AddonBuilder' \
            /v path /f "/reg:$registry_view" >/dev/null 2>&1 || true
        run_proton reg.exe delete \
            'HKLM\Software\Bohemia Interactive\AddonBuilder' \
            /v exe /f "/reg:$registry_view" >/dev/null 2>&1 || true
    done
    run_proton reg.exe delete \
        'HKCU\Software\Wine\AppDefaults\ObjectBuilder.exe' \
        /v Version /f >/dev/null 2>&1 || true
else
    printf 'Warning: Proton or its prefix is unavailable; registry cleanup was skipped.\n' >&2
fi

printf 'Removing launchers...\n'
for launcher in \
    "arma3-object-builder.desktop" \
    "arma3-addon-builder.desktop" \
    "arma3-texview2.desktop"; do
    rm -f "$APP_DIR/$launcher" "$DESKTOP_DIR/$launcher"
done

restore_drive() {
    local drive="$1"
    local installed_target="$2"
    local previous_target="$3"
    local link="$PREFIX/dosdevices/$drive:"
    local current_target

    current_target="$(readlink "$link" 2>/dev/null || true)"
    if [[ "$current_target" != "$installed_target" ]]; then
        printf 'Warning: %s: was changed after installation; leaving it untouched.\n' \
            "${drive^^}" >&2
        return
    fi

    rm -f "$link"
    if [[ -n "$previous_target" ]]; then
        ln -s "$previous_target" "$link"
    fi
}

printf 'Restoring drive mappings...\n'
restore_drive s "$STEAMAPPS" "${PREVIOUS_S:-}"
restore_drive h "$HOME" "${PREVIOUS_H:-}"
restore_drive l "$DESKTOP_DIR" "${PREVIOUS_L:-}"
restore_drive p "$PREFIX/drive_c/Arma3Work" "${PREVIOUS_P:-}"

if [[ -L "$PROJECT_LINK" &&
      "$(readlink "$PROJECT_LINK" 2>/dev/null || true)" == "$PREFIX/drive_c/Arma3Work" ]]; then
    rm -f "$PROJECT_LINK"
fi

command -v update-desktop-database >/dev/null &&
    update-desktop-database "$APP_DIR" >/dev/null 2>&1 || true

rm -f "$STATE_FILE"
rm -f "$MAPPINGS_FILE"
rmdir "$STATE_DIR" 2>/dev/null || true

printf '\nUninstallation complete.\n'
printf 'Project data and copied TexView support files were preserved.\n'
